/**
 * Sprint PR — builds gh CLI commands for sprint-end PR creation and review.
 *
 * Pure functions that generate command strings and structured data.
 * The lead agent executes these commands via Bash; this module never
 * touches the file system or spawns processes itself.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface SprintPrConfig {
  sprintBranch: string;
  baseBranch: string;
  sprintId: string;
  sprintName: string;
  workItems: SprintWorkItemSummary[];
}

export interface SprintWorkItemSummary {
  id: string;
  title: string;
  status: string;
}

export interface PrCreateCommand {
  command: string;
  title: string;
  body: string;
}

export interface ReviewComment {
  path: string;
  line: number;
  body: string;
}

export interface PrReviewCommand {
  command: string;
  event: 'COMMENT' | 'APPROVE' | 'REQUEST_CHANGES';
  body: string;
}

export interface PrCommentCommand {
  command: string;
  path: string;
  line: number;
  body: string;
}

// ---------------------------------------------------------------------------
// PR body generation
// ---------------------------------------------------------------------------

export function buildPrBody(config: SprintPrConfig): string {
  const lines: string[] = [
    `## Sprint: ${config.sprintName}`,
    '',
    `Sprint ID: \`${config.sprintId}\``,
    `Branch: \`${config.sprintBranch}\` → \`${config.baseBranch}\``,
    '',
    '### Work Items',
    '',
    '| ID | Title | Status |',
    '|----|-------|--------|',
  ];

  for (const wi of config.workItems) {
    lines.push(`| ${wi.id} | ${wi.title} | ${wi.status} |`);
  }

  lines.push('');
  lines.push('---');
  lines.push('Generated by Hive Orchestration System');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// PR title generation
// ---------------------------------------------------------------------------

export function buildPrTitle(config: SprintPrConfig): string {
  return `[hive] ${config.sprintName} (${config.sprintId})`;
}

// ---------------------------------------------------------------------------
// gh pr create command
// ---------------------------------------------------------------------------

export function buildPrCreateCommand(config: SprintPrConfig): PrCreateCommand {
  const title = buildPrTitle(config);
  const body = buildPrBody(config);

  // Escape single quotes in title and body for shell safety
  const escapedTitle = title.replace(/'/g, "'\\''");
  const escapedBody = body.replace(/'/g, "'\\''");

  const command = [
    'gh pr create',
    `--base '${config.baseBranch}'`,
    `--head '${config.sprintBranch}'`,
    `--title '${escapedTitle}'`,
    `--body '${escapedBody}'`,
  ].join(' ');

  return { command, title, body };
}

// ---------------------------------------------------------------------------
// gh pr review command
// ---------------------------------------------------------------------------

export function buildPrReviewCommand(
  prNumber: number,
  event: 'COMMENT' | 'APPROVE' | 'REQUEST_CHANGES',
  body: string,
): PrReviewCommand {
  const escapedBody = body.replace(/'/g, "'\\''");

  const command = [
    `gh pr review ${prNumber}`,
    `--${event.toLowerCase().replace(/_/g, '-')}`,
    `--body '${escapedBody}'`,
  ].join(' ');

  return { command, event, body };
}

// ---------------------------------------------------------------------------
// gh api comment command (for inline review comments)
// ---------------------------------------------------------------------------

export function buildPrCommentCommand(
  owner: string,
  repo: string,
  prNumber: number,
  commitSha: string,
  comment: ReviewComment,
): PrCommentCommand {
  const payload = {
    body: comment.body,
    commit_id: commitSha,
    path: comment.path,
    line: comment.line,
    side: 'RIGHT',
  };

  const payloadJson = JSON.stringify(payload);

  const command = `printf '%s' '${payloadJson.replace(/'/g, "'\\''")}' | gh api repos/${owner}/${repo}/pulls/${prNumber}/comments -X POST --input -`;

  return {
    command,
    path: comment.path,
    line: comment.line,
    body: comment.body,
  };
}

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

export function validateSprintPrConfig(config: SprintPrConfig): string[] {
  const errors: string[] = [];

  if (!config.sprintBranch) {
    errors.push('sprintBranch is required');
  }
  if (!config.baseBranch) {
    errors.push('baseBranch is required');
  }
  if (!config.sprintId) {
    errors.push('sprintId is required');
  }
  if (!config.sprintName) {
    errors.push('sprintName is required');
  }
  if (!config.workItems || config.workItems.length === 0) {
    errors.push('workItems must contain at least one item');
  }

  // Check that all work items are MERGED
  const nonMerged = (config.workItems || []).filter(wi => wi.status !== 'MERGED');
  if (nonMerged.length > 0) {
    errors.push(
      `All work items must be MERGED before creating sprint PR. Non-merged: ${nonMerged.map(wi => wi.id).join(', ')}`,
    );
  }

  return errors;
}

// ---------------------------------------------------------------------------
// Check prerequisites (is gh available, does remote exist)
// ---------------------------------------------------------------------------

export interface PrerequisiteCheck {
  ready: boolean;
  missing: string[];
}

export function checkPrerequisites(
  ghAvailable: boolean,
  hasRemote: boolean,
): PrerequisiteCheck {
  const missing: string[] = [];

  if (!ghAvailable) {
    missing.push('gh CLI is not available — install GitHub CLI to create PRs');
  }
  if (!hasRemote) {
    missing.push('No git remote configured — push the repository to GitHub first');
  }

  return { ready: missing.length === 0, missing };
}
