import { describe, it, expect } from 'vitest';
import {
  buildPrBody,
  buildPrTitle,
  buildPrCreateCommand,
  buildPrReviewCommand,
  buildPrCommentCommand,
  validateSprintPrConfig,
  checkPrerequisites,
  type SprintPrConfig,
  type ReviewComment,
} from '../../src/sprint-pr.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeConfig(overrides: Partial<SprintPrConfig> = {}): SprintPrConfig {
  return {
    sprintBranch: 'sprint/sprint-1',
    baseBranch: 'master',
    sprintId: 'sprint-1',
    sprintName: 'Auth Rewrite',
    workItems: [
      { id: 'wi-1', title: 'Add login endpoint', status: 'MERGED' },
      { id: 'wi-2', title: 'Add logout endpoint', status: 'MERGED' },
    ],
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// buildPrTitle
// ---------------------------------------------------------------------------

describe('buildPrTitle', () => {
  it('includes sprint name and id', () => {
    const title = buildPrTitle(makeConfig());
    expect(title).toBe('[hive] Auth Rewrite (sprint-1)');
  });

  it('handles names with special characters', () => {
    const title = buildPrTitle(makeConfig({ sprintName: "Fix O'Brien's bug" }));
    expect(title).toContain("Fix O'Brien's bug");
  });
});

// ---------------------------------------------------------------------------
// buildPrBody
// ---------------------------------------------------------------------------

describe('buildPrBody', () => {
  it('includes sprint header', () => {
    const body = buildPrBody(makeConfig());
    expect(body).toContain('## Sprint: Auth Rewrite');
  });

  it('includes sprint id', () => {
    const body = buildPrBody(makeConfig());
    expect(body).toContain('`sprint-1`');
  });

  it('includes branch arrow', () => {
    const body = buildPrBody(makeConfig());
    expect(body).toContain('`sprint/sprint-1` → `master`');
  });

  it('includes work items table header', () => {
    const body = buildPrBody(makeConfig());
    expect(body).toContain('| ID | Title | Status |');
    expect(body).toContain('|----|-------|--------|');
  });

  it('lists all work items', () => {
    const body = buildPrBody(makeConfig());
    expect(body).toContain('| wi-1 | Add login endpoint | MERGED |');
    expect(body).toContain('| wi-2 | Add logout endpoint | MERGED |');
  });

  it('includes footer', () => {
    const body = buildPrBody(makeConfig());
    expect(body).toContain('Generated by Hive Orchestration System');
  });

  it('handles empty work items array', () => {
    const body = buildPrBody(makeConfig({ workItems: [] }));
    expect(body).toContain('### Work Items');
    // Table header should still be present even with no rows
    expect(body).toContain('| ID | Title | Status |');
  });
});

// ---------------------------------------------------------------------------
// buildPrCreateCommand
// ---------------------------------------------------------------------------

describe('buildPrCreateCommand', () => {
  it('generates valid gh pr create command', () => {
    const result = buildPrCreateCommand(makeConfig());
    expect(result.command).toContain('gh pr create');
    expect(result.command).toContain("--base 'master'");
    expect(result.command).toContain("--head 'sprint/sprint-1'");
  });

  it('returns title and body separately', () => {
    const result = buildPrCreateCommand(makeConfig());
    expect(result.title).toBe('[hive] Auth Rewrite (sprint-1)');
    expect(result.body).toContain('## Sprint: Auth Rewrite');
  });

  it('escapes single quotes in title', () => {
    const result = buildPrCreateCommand(makeConfig({ sprintName: "O'Reilly" }));
    expect(result.command).toContain("O'\\''Reilly");
  });

  it('escapes single quotes in body', () => {
    const result = buildPrCreateCommand(
      makeConfig({
        workItems: [{ id: 'wi-1', title: "Fix it's bug", status: 'MERGED' }],
      }),
    );
    expect(result.command).toContain("it'\\''s");
  });

  it('includes --title and --body flags', () => {
    const result = buildPrCreateCommand(makeConfig());
    expect(result.command).toContain('--title');
    expect(result.command).toContain('--body');
  });
});

// ---------------------------------------------------------------------------
// buildPrReviewCommand
// ---------------------------------------------------------------------------

describe('buildPrReviewCommand', () => {
  it('generates COMMENT review command', () => {
    const result = buildPrReviewCommand(42, 'COMMENT', 'Looks good overall');
    expect(result.command).toContain('gh pr review 42');
    expect(result.command).toContain('--comment');
    expect(result.command).toContain('Looks good overall');
    expect(result.event).toBe('COMMENT');
  });

  it('generates APPROVE review command', () => {
    const result = buildPrReviewCommand(42, 'APPROVE', 'Ship it');
    expect(result.command).toContain('--approve');
    expect(result.body).toBe('Ship it');
  });

  it('generates REQUEST_CHANGES review command', () => {
    const result = buildPrReviewCommand(42, 'REQUEST_CHANGES', 'Fix tests');
    expect(result.command).toContain('--request-changes');
    expect(result.body).toBe('Fix tests');
  });

  it('escapes single quotes in body', () => {
    const result = buildPrReviewCommand(42, 'COMMENT', "Don't merge yet");
    expect(result.command).toContain("Don'\\''t");
  });

  it('preserves pr number', () => {
    const result = buildPrReviewCommand(99, 'APPROVE', 'LGTM');
    expect(result.command).toContain('gh pr review 99');
  });
});

// ---------------------------------------------------------------------------
// buildPrCommentCommand
// ---------------------------------------------------------------------------

describe('buildPrCommentCommand', () => {
  const comment: ReviewComment = {
    path: 'src/auth.ts',
    line: 42,
    body: 'Consider using a constant here',
  };

  it('generates gh api command targeting correct endpoint', () => {
    const result = buildPrCommentCommand('acme', 'hive', 7, 'abc123', comment);
    expect(result.command).toContain('gh api repos/acme/hive/pulls/7/comments');
  });

  it('uses POST method', () => {
    const result = buildPrCommentCommand('acme', 'hive', 7, 'abc123', comment);
    expect(result.command).toContain('-X POST');
  });

  it('includes path, line, and body in result', () => {
    const result = buildPrCommentCommand('acme', 'hive', 7, 'abc123', comment);
    expect(result.path).toBe('src/auth.ts');
    expect(result.line).toBe(42);
    expect(result.body).toBe('Consider using a constant here');
  });

  it('includes commit_id in payload', () => {
    const result = buildPrCommentCommand('acme', 'hive', 7, 'abc123', comment);
    expect(result.command).toContain('abc123');
  });
});

// ---------------------------------------------------------------------------
// validateSprintPrConfig
// ---------------------------------------------------------------------------

describe('validateSprintPrConfig', () => {
  it('returns no errors for valid config', () => {
    const errors = validateSprintPrConfig(makeConfig());
    expect(errors).toEqual([]);
  });

  it('requires sprintBranch', () => {
    const errors = validateSprintPrConfig(makeConfig({ sprintBranch: '' }));
    expect(errors).toContain('sprintBranch is required');
  });

  it('requires baseBranch', () => {
    const errors = validateSprintPrConfig(makeConfig({ baseBranch: '' }));
    expect(errors).toContain('baseBranch is required');
  });

  it('requires sprintId', () => {
    const errors = validateSprintPrConfig(makeConfig({ sprintId: '' }));
    expect(errors).toContain('sprintId is required');
  });

  it('requires sprintName', () => {
    const errors = validateSprintPrConfig(makeConfig({ sprintName: '' }));
    expect(errors).toContain('sprintName is required');
  });

  it('requires at least one work item', () => {
    const errors = validateSprintPrConfig(makeConfig({ workItems: [] }));
    expect(errors).toContain('workItems must contain at least one item');
  });

  it('requires all work items to be MERGED', () => {
    const errors = validateSprintPrConfig(
      makeConfig({
        workItems: [
          { id: 'wi-1', title: 'Done', status: 'MERGED' },
          { id: 'wi-2', title: 'Not done', status: 'IN_PROGRESS' },
        ],
      }),
    );
    expect(errors.length).toBe(1);
    expect(errors[0]).toContain('wi-2');
    expect(errors[0]).toContain('MERGED');
  });

  it('lists multiple non-merged work items', () => {
    const errors = validateSprintPrConfig(
      makeConfig({
        workItems: [
          { id: 'wi-1', title: 'A', status: 'REVIEW' },
          { id: 'wi-2', title: 'B', status: 'TESTING' },
        ],
      }),
    );
    expect(errors[0]).toContain('wi-1');
    expect(errors[0]).toContain('wi-2');
  });

  it('collects multiple errors at once', () => {
    const errors = validateSprintPrConfig({
      sprintBranch: '',
      baseBranch: '',
      sprintId: '',
      sprintName: '',
      workItems: [],
    });
    expect(errors.length).toBeGreaterThanOrEqual(5);
  });
});

// ---------------------------------------------------------------------------
// checkPrerequisites
// ---------------------------------------------------------------------------

describe('checkPrerequisites', () => {
  it('returns ready when gh and remote are available', () => {
    const result = checkPrerequisites(true, true);
    expect(result.ready).toBe(true);
    expect(result.missing).toEqual([]);
  });

  it('reports missing gh CLI', () => {
    const result = checkPrerequisites(false, true);
    expect(result.ready).toBe(false);
    expect(result.missing).toHaveLength(1);
    expect(result.missing[0]).toContain('gh CLI');
  });

  it('reports missing remote', () => {
    const result = checkPrerequisites(true, false);
    expect(result.ready).toBe(false);
    expect(result.missing).toHaveLength(1);
    expect(result.missing[0]).toContain('remote');
  });

  it('reports both missing', () => {
    const result = checkPrerequisites(false, false);
    expect(result.ready).toBe(false);
    expect(result.missing).toHaveLength(2);
  });
});
